cooking:
  base:
    health-regen: 1.0
  leveling:
    saturation-increase: 1.0
    extra-hunger-given: 1.0

farming:
  base:
    double-chance: 5.0
  leveling:
    double-chance: 1.0

husbandry:
  # Number from 0%-100%
  base-increased-drop-chance: 5.0

  # Number from 0%-100%
  base-increased-drops-from-kills: 5.0

  # Number from 0%-100%
  base-chance-of-multi-breeding: 5.0

  # Number from 0%-100%
  base-instant-adult-while-breeding: 5.0

  # Number from 0%-100%
  increased-drop-chance: 1.0

  increased-drops-from-kills: 5.0

  # Number from 0%-100%
  chance-of-multi-breeding-increase: 5.0

  # Number from 0%-100%
  instant-adult-while-breeding-increase: 0.1

  max-multi-breeding-chance: 80.0
  max-instant-adult-chance: 80.0

lockpicking:
  base:
    # Number from 0%-100%
    success-chance: 5.0
    break-pick-chance: 75.0

  leveling:
    # Number from 0%-100%
    chance-increase: 5.0
    break-pick-chance: 1.0

ranged:
  damage-increase: 0.5
  crit-damage-multiplier: 1.0
  max-crit-chance: 80.0
  crit-chance-increase: 0.1
  crit-damage-mult: 2.0
  reload-speed: 1.0 #maybe
  increase-per-level: 1.0

salvage:
  base:
    # Number from 0%-100%
    base-resource-return: 10.0

  leveling:
    # Number from 0%-100%
    resource-return-increase: 1.0

stealth:
  default-radius: 35.0
  detection-reduction: 0.01

stamina:
  stamina-increase-per-level: 1.0
  default-regen-rate: 1.0

strength:
  health-increase-per-level: 1.0
  mine-speed-multiplier: 1.0 #maybe
  jump-height-multiplier: 1.0 #maybe
  max-crit-chance: 80.0
  #% increase per level
  damage-increase: 0.1
  # number starting from 0.0. Equation is: final damage = damage + (original damage * (unarmed level * crit chance increase))
  crit-chance-increase: 0.1
  crit-damage-multiplier: 2.0
  increase-per-level: 1.0